### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by zecompadre** [madskristensen/WebEssentials2013#1918] opened 2015-07-20 13:24 UTC
20/07/2015 14:21:11: System.NullReferenceException: Object reference not set to an instance of an object.
   at MadsKristensen.EditorExtensions.FileHelpers.RelativePath(String absolutePath, String relativeTo)
   at MadsKristensen.EditorExtensions.Helpers.CssUrlNormalizer.FixPath(String url)
   at MadsKristensen.EditorExtensions.Helpers.CssUrlNormalizer.Visit(ParseItem parseItem)
   at Microsoft.CSS.Core.ComplexItem.Accept(ICssSimpleTreeVisitor visitor)
   at Microsoft.CSS.Core.ComplexItem.Accept(ICssSimpleTreeVisitor visitor)
   at Microsoft.CSS.Core.ComplexItem.Accept(ICssSimpleTreeVisitor visitor)
   at Microsoft.CSS.Core.ComplexItem.Accept(ICssSimpleTreeVisitor visitor)
   at Microsoft.CSS.Core.ComplexItem.Accept(ICssSimpleTreeVisitor visitor)
   at MadsKristensen.EditorExtensions.Helpers.CssUrlNormalizer.NormalizeUrls(BlockItem tree, String targetFile, String oldBasePath)
   at MadsKristensen.EditorExtensions.BundleGenerator.<CombineFiles>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleGenerator.<MakeBundle>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<GenerateAsync>d__2d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MadsKristensen.EditorExtensions.BundleFilesMenu.<UpdateBundleAsync>d__22.MoveNext()
20/07/2015 14:21:11: Error generating the bundle. See output window for details

==========================

when u have this kind of "url:"

and u have the "adjustRelativePaths" = true

-> behavior: url(#default#VML);

or

-> 		background-image: url('data:image/gif;base64,R0lGODlhKAAoAPMBAPX58ZC+arjVoOny4aTKhe315szhuuDt1aTKhuXw3NHkwpC+a+/26dDjwPL37gAAACH/C05FVFNDQVBFMi4wAwEAAAAh/hoiQ3JlYXRlZCB3aXRoIENoaW1wbHkuY29tIgAh+QQJCgABACwAAAAAKAAoAAAE8jDISau9OOvNO2VJKCYMJZwoah1se1SJIc9GYqbp6rIwPdsTXK6y41FivtpNKNDtekmghHlyuqA+aYDaJBaxNC3X2gL/lkLPZyQqBanquHxOr9vvkkFjz+cP8BYNBIOEhA0VDAWKim5qgoWFhxQFA5WVBXKPkIOSE5SWA5hxmpudEp+Woo6bhhWol5msnK6gobGypgGJiwWNHqSQuYDAkYAVen19f8bMzc4SC9HS0wvP1NeIvL0Wu4u+19S0oKqeteTg0+KpFq+2E+jS6rDy7tDw1ZPm7Prv9/Tkp/jZg5eNly8J3RhRuIevGUNr/p5JvBMBACH5BAkKAAAALAAAAAAoACgAAATxEMhJq7046827n0wijgljMUWamtXhvkeVGHRtJFYx7HthwS+ZrYar6HgDXwsYo8yGtxwy+WMKoUXKkaekMJuT5zA72faqwOv4pFqhYWob+cMJkUQsun7P7/v/gIEZAoSFhWxteR+GjFJIXYuMh0ZTkB6Sk1qVe5iEjlycnZ9nep0CiCqKl6KCFaatsLGysAG1trcBEgMKvL29A3S4whIKBMbHxwoVKIkUwrjEyNLKmo/Oz7bR0smU1hPY2QDF28bUZZvf4Lni5OXdoOng2uTmEmZU8djz2/UAzKnX5LFr12+DunXj6AVTp8uXQ2CzIvaJAAAh+QQJCgAAACwAAAAAKAAoAAAE8hDISau9OOvNu/8TU4wjY4lkYVZH6x5XMcxzYcn0YLNvG+e6G3BH6fmEOeIER1NKjDBkU1qzQH9JapDXu6BIK8q3ZDWCzui0es1uu99wgCNBryccp5QKnTD4/wYJWk4dfYB+ghVMVWeGh4kUi1sgjoCQS0N8h4iDmpuXEmN7jZuBcRRzdnR4p62urxUBsrO0ARIDCrm6ugMgtb8SCgjDxMQKEwLJysoUv7XBxdHHEsvVzc6z0NHGyNXME9jZAMLbw9MA3t8S4bLa5efpydfh7tvw8fPY9dLd6fnO+4rd8weOXUBu1PAVpAcA165dvWBJbBUBACH5BAkKAAAALAAAAAAoACgAAATyEMhJq7046827/xNTjCNjiWRhVii5VsUgy4UVz0MN4/l1zzrKj2bjBYXGIu4oGfaUQChxt/QlqVHslJVSnbqvEBhELpvP6LQ6E2i734F1BU6XU+hw8mHPP8zxbnp9e3+AcSCDhHeGhx+JfouGgoOFgJN9lXiXfJl1dhKMjZ+jpGkDCqipqQOkCgSvsLAKEwK1trYUDAm7vAlhrrGxsxK3xRQJBsnKBgkUwMGvwwDFt8fLys0Tz9DS1LgTyNfMztCytN4C1uLZEtvB3ejq1+wA7sLn3vLL9PbmxPHgxI3TVi4aPmq5evEKc0qVKlalIkr0EAEAIfkECQoAAAAsAAAAACgAKAAABPkQyEmrvbiGzXvIIOiNYWmNHsUULMtYa1u8FNpRxaDrhZXvg17NtsEBg76jcEIsTn675VOpaRqBUgmUVyVeo0ls16aSzWBmGtNqagOaH7d8Tq/bJwOFfr8f3DEKBIKDgwp/F4GEhIZyMS1qEomKgoxuW0gUkpOVbZdZmoqcJp4VoItzpJmThahUqqsEoiWOLqWwsYcWeXx8frm/wMHCdQLFxsYqCcrLCZBtx9AUCQbU1QYJFQfa2wcW0MfS1tXYFNzb3t/F4eLX2ebdFenqE9Ps5BPv8BTyAuvi9xLyoUvnzxpAAALjySs4zp25gd+SMVPmbJjFixgzRAAAIfkECQoAAAAsAAAAACgAKAAABPgQyEmrvbgOxXsfUiCOZJBdCqGuqxKW5WmlLOsCcDwxRd8zFVpNdcuRKIWBUlkIDlsvo2mSXA6aFOGwKJ1KqkvsRFvjSpHWq/NJMBvRVrGEbIu+d77f+unOyTQegSA4XX+Gh4iJiouMhgKPkJCNMpGVizx5QBWVkYtgTBackoqfapuiAp5pchKoqaSroaiqcbKil3kFmhSuk76/wMHCw78MCcfICbvECQbOzwYJFQfU1QcWmD7LEs3QztIU1tUWpawA3d7gE+LU5LEV6NDqEuzXFeUW8c/zAPXutfC8fZvG7l+YfAKjERSHLdc2AMaSHXtIrKLFi8EiAAAh+QQJCgAIACwAAAAAKAAoAAAE9BDJSau9OOehuveDFIxkGVBCqqqTQrwwrIimia5rG+8zUtsTXE7i2slov9FNKNAZX70kaSl0PqPSU5DZJD6hyCQVZzVipeMhongN/9Is7/cs1lQ4n0/Il7X7/4CBgoOEGAAJiIkJAIV+CQaQkQYJhAwFl5cMFo+SkJSDBQOiogWbnZ6EoaMDpRWcnZ+CqqOtFK+SsYGzpKanuYC7rL2wlZiZFoeKiIyNzc7P0NHS09SBB9fYBxaWxpoV3JjeFdnYFsG1E+cX5Nfmq8IV6hbs2vHv6BLy4+zuq/gI+ijQ60eLIK95/L4ZKyBuArhj1SJKnEgRQwQAIfkECQoAAAAsAAAAACgAKAAABPQQyEmrvTjrDUb7IDhQTmKeiUMJbNtODSHPc0MlRq4byeq6MJrQNsHtcr3JDyiJCWu3I9K3FASfMqLEeExKqqwrVgvg7rwAsLWJzUalaLX4STbr4uD5kIQ6qZR5bG1kHIUeISEjhYuMjY6PjAGSk5QBkBqVmRUHnJ0HjpmVm56coKGTo6Smp5YUpKWNrJKpnquntJ22obiwkbKXGbKtwBbCxMfIycrLjwwFz88MFs7QBdIV1NDXFQUD3t4FFt3fA+Hc5OUX49/mFOvg4ujt7vLx5PMS7+n27Pzw5/fU1QPYj+A/bNWsTUu4bUK2aMwiSpxIcVEEADs=')

if i comment this lines the error disapear :)

error starts since last update.

tks

**Comment by rSffsE** [comment] 2015-07-22 08:58
I have experienced this same error since upgrading to Web Essentials v2.6.12
It happens to me when bundling font-awesome.css with css in another path and having
```xml
<adjustRelativePaths>true</adjustRelativePaths>
```
in the bundle settings file

Looks like Web Essentials bundling is now throwing the Exception above when it tries to adjust the path on the font awesome css rule:
```css
@font-face {
  src: url('../fonts/fontawesome-webfont.eot?v=4.1.0'); 
}
```
Looking forward to a fix to Web Essentials as soon as you can!

**Comment by am11** [comment] 2015-07-22 17:51
Actually the exception log is a result of false-positive due to `FileSystemWatcher` firing the change event twice.

As an end-consumer, you can observe the false positive from the status bar (at the bottom of VS) which shows "Bundle generated" from the bundling operation, even after this exception is thrown and the correct output is written to the file. Another clue is, if you make changes in source files and save, and the generated .css and .min.css were already opened in VS, it will prompt a message resembling the description: "those files have been modified outside the editor, do you want to reload".

The false-positive is fixed by b1ad746 via #1920.

/cc @madskristensen, @SLaks

**Comment by rSffsE** [comment] 2015-07-23 06:22
@am11 It's not a false positive for me.  The reason I found the bug is that my bundled .css and .min.css files are not updating and I was wondering why my changes aren't having any effect!

**Comment by am11** [comment] 2015-07-23 07:14
@rSffsE, strange. I tested with the piece of CSS code you provided with latest master before making the changes, and it was updating both .css and .min.css and throwing the exception due to double FWS event firing.

**Comment by zecompadre** [comment] 2015-07-23 09:36
It's not a false positive for me too.

I am using Visual Studio 2013 Update 5 and Web Essentials 2013 for Update 4/5 v2.6.12

/cc @madskristensen, @SLaks

**Comment by am11** [comment] 2015-07-23 11:01
@zecompadre please provide the proper repro steps (preferably sample project) as per the bug reporting guideline => https://github.com/madskristensen/WebEssentials2013/blob/master/CONTRIBUTING.md#bug-reports

**Comment by rSffsE** [comment] 2015-07-23 23:20
@am11 
The steps to reproduce the problem for me are:
* on Visual Studio 2013 U4 and WE v2.6.12
* create a new web blank web application blank
* create a ./css directory, and a new stylesheet in there, eg main.css
* create a subdirectory under /css and put some css files under there that contain relative paths, eg for [font-awesome] (http://fortawesome.github.io/Font-Awesome/) to /css/fa/css/font-awesome.css
* create a bundle for /css/main.css and /css/fa/css/font-awesome.css with 
```
<adjustRelativePaths>true</adjustRelativePaths>
```
* the bundle will fail to generate, and will display the error in the OP in the Build Output.

Please see screenshot attached.
![2015-07-24 08_43_42-webapplication3 - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/1900751/8864426/f05e2d9e-31e0-11e5-8f91-864d1ceb85d8.png)

**Comment by zecompadre** [comment] 2015-07-24 14:54
exact the same were :(

**Comment by am11** [comment] 2015-07-24 16:30
I had  a long day at work. I try to replicate the issue locally over the weekend. 
Nonetheless, thanks for the detailed repro steps @rSffsE ! :+1:

**Comment by am11** [comment] 2015-07-25 21:59
I was able to reproduce it.
Fixed by #1924.

**Closed** 2015-07-25 23:24 UTC

**Comment by zecompadre** [comment] 2015-07-27 08:51
How can i update to this fix ?

I've tried the Nightly Build but cant install 

![image](https://cloud.githubusercontent.com/assets/1632647/8901943/e26d18e2-3444-11e5-8d24-8f2497ec5d7e.png)

i've the latest VS2013

![image](https://cloud.githubusercontent.com/assets/1632647/8901953/fcae513a-3444-11e5-9241-77312d3a20b6.png)

tks

**Comment by zecompadre** [comment] 2015-07-28 13:48
updated to v2.6.13, solved :) @am11 tks !
