### ISSUE TITLE
File path too long, unable to compile as it is throwing error

### ISSUE THREAD

**Issue by jerriclynsjohn** [madskristensen/WebEssentials2013#1452] opened 2014-08-28 18:02 UTC
The WebEssential2013 for Update 3

I'm not able to compile since the below is posing an error diagnostic.

The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

Unable to copy file "Resources\nodejs\tools\node_modules\autoprefixer\node_modules\fs-extra\node_modules\mkdirp\node_modules\minimist\index.js" to "C:\Users\Jerric Lyns John\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\Mads Kristensen\Web Essentials 2013 for Update 3\2.3.2\Resources\nodejs\tools\node_modules\autoprefixer\node_modules\fs-extra\node_modules\mkdirp\node_modules\minimist\\index.js".

**Comment by polyphenolic** [comment] 2015-01-05 21:36
Late to the party on this but I also experienced this today. The problematic path would have been "C:\Users\Brad.Christensen\AppData\Local\Microsoft\VisualStudio\12.0Exp\Extensions\Mads Kristensen\Web Essentials 2013 for Update 4\2.5.3.1\Resources\nodejs\tools\node_modules\autoprefixer\node_modules\fs-extra\node_modules\mkdirp\node_modules\minimist\..." which is just a few characters over the 248 character limit for the directory path. Obviously my username must be a little longer than that of other people who've been building Web Essentials since that's kinda the only variable here :)

So you could change your username, but what I did to get around it was to change the author in the manifest (Source.extension.xsixmanifest) from "Mads Kristensen" to something shorter (say, "Mads") which is then reflected in the path. For me that then makes the path a couple of characters shorter than the maximum length (hopefully that works for your username too).

**Comment by markian2** [comment] 2015-01-17 01:17
I recommended u to try "Long Path Tool" program .before I have problem like this. and after I found long path tool and now my problem solved

**Comment by japj** [comment] 2015-05-14 09:22
I just also experienced this issue, see also http://pastebin.com/E09UqrsF

I am not sure why the build is actually copying files to AppData\Local, that makes the paths needlessly long.

Is there a good solution to be able to build this project "out of the box" normally?

**Comment by SLaks** [comment] 2015-05-15 20:27
It copies to `AppData\Local` because that's where VS extensions are installed.  

The problem is that my module-collapsing code (which is supposed to flatten all of those deep directories) is skipping everything.

**Comment by SLaks** [comment] 2015-06-01 00:04
This problem is completed fixed by #1868

**Closed** 2015-06-01 02:06 UTC

**Comment by Damienbarifon** [comment] 2015-10-13 13:42
Try to long path tool software. It is very helpful.

**Comment by ashley200** [comment] 2017-07-28 22:30
Damienbarifon is right. Long PAth tool helped me too.
