### ISSUE TITLE
Virus Warning

### ISSUE THREAD

**Issue by Code-Bear** [madskristensen/WebEssentials2013#1740] opened 2015-01-22 16:36 UTC
I am sure this is a false positive but I wanted to warn you that Avast is blocking gifsicle.exe as a possible threat.

![image](https://cloud.githubusercontent.com/assets/6423675/5859745/a6795424-a22a-11e4-9e2b-fed1cc6d98f9.png)

**Comment by madskristensen** [comment] 2015-01-22 17:11
Dupe of #1508

**Closed by madskristensen** 2015-01-22 17:11 UTC
